In [1]:
import numpy as np

slicing to numpy arrays

In [ ]:

nparr = np.array([[2,3,45,6], [20,43,23,10], [100,0,23,15]])
flatted_Arr = nparr.flatten()
# nparr[2]
print(flatted_Arr[3 : ])
print(flatted_Arr[ : 9])
print(flatted_Arr[ :: 2]) #index add  +2 +2..

we cant alter the slice of a arry it will alwese alter the originar array so we have to do a copy of that

In [26]:
slice_Arr = flatted_Arr[2:5]
# slice_Arr[1] = 1000  #we have to do copy
print(slice_Arr)
print(flatted_Arr)

[45  6 20]
[  2   3  45   6  20  43  23  10 100   0  23  15]


In [31]:
slice_Arr = flatted_Arr[2:5].copy()
slice_Arr
slice_Arr[1] = 1000
print(slice_Arr)
print(flatted_Arr)

[  45 1000   20]
[  2   3  45   6  20  43  23  10 100   0  23  15]


fancy indexing

In [50]:
# print(flatted_Arr[2,3,4])
idx = [0,2,4]
print(flatted_Arr[idx])


[10 30 50]


In [51]:
idx = flatted_Arr > 10
print(flatted_Arr[idx])

[20 30 40 50]
