In [2]:
import numpy as np

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.full([2,3], 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [52]:
np.linspace(1,150,15)

array([  1.        ,  11.64285714,  22.28571429,  32.92857143,
        43.57142857,  54.21428571,  64.85714286,  75.5       ,
        86.14285714,  96.78571429, 107.42857143, 118.07142857,
       128.71428571, 139.35714286, 150.        ])

In [55]:
arr = np.array([[2,3,4,5], [23,66,3,55]])
print("size :", arr.size)
print("shape :", arr.shape)
print("dimension :", arr.ndim)
print("data type :", arr.dtype)

size : 8
shape : (2, 4)
dimension : 2
data type : int32
flat array is: [ 2  3  4  5 23 66  3 55]


In [51]:
# data type change
arr = np.array([[2,3,4,5], [23,66,3,55]], dtype = np.float32)
arr.dtype

dtype('float32')

In [58]:
reshaped_arr = arr.reshape([4,2])
print("flat array is:", arr.flatten())
arr

flat array is: [ 2  3  4  5 23 66  3 55]


array([[ 2,  3,  4,  5],
       [23, 66,  3, 55]])