In [1]:
import numpy as np

In [5]:
arr1d = np.array([12,43,90,2,0,])

In [4]:
arr2d = np.array([[1,2,3], 
                  [12,3,44]])
arr2d

array([[ 1,  2,  3],
       [12,  3, 44]])

In [9]:
print("rows sum 1d :", np.sum(arr1d, axis = 0))
print("rows sum 2d :", np.sum(arr2d, axis = 0))
print("rows sum 2d :", np.sum(arr2d, axis = 1))

rows sum 1d : 147
rows sum 2d : [13  5 47]
rows sum 2d : [ 6 59]


In [20]:
print(arr2d[0])
print(arr2d[:][1])

[1 2 3]
[12  3 44]


slicing of multid

In [28]:
print(arr2d[0:,1:])

[[ 2  3]
 [ 3 44]]


In [40]:
arr3d = np.array([
                   [[12,32,3],
                   [10,0,22]], 
                    
                   [[90,9,3], 
                   [40,50,60]]
                 ])
arr3d.ndim

3

indexing in 3d array

In [41]:
arr3d[1][1][1]

50

In [43]:
arr3d[:, 1, :]
arr3d[:, 1, 1]

array([ 0, 50])

In [47]:
print("arr axis0 sum :", np.sum(arr3d, axis = 0))
print("arr axis1 sum :", np.sum(arr3d, axis = 1))
print("arr axis2 sum :", np.sum(arr3d, axis = 2))

arr axis0 sum : [[102  41   6]
 [ 50  50  82]]
arr axis1 sum : [[ 22  32  25]
 [130  59  63]]
arr axis2 sum : [[ 47  32]
 [102 150]]


In [49]:
arr2d[:,0] = 0
print(arr2d)
arr3d[:, 1, :] = 3
print(arr3d)

[[ 0  2  3]
 [ 0  3 44]]
[[[12 32  3]
  [ 3  3  3]]

 [[90  9  3]
  [ 3  3  3]]]
