In [1]:
import numpy as np

In [3]:
arr = np.array([[12,3,4,55], [22,0,33,2]])
arr + 239

array([[251, 242, 243, 294],
       [261, 239, 272, 241]])

broadcasting 10 through each elements of arr no need of extra memory

arr1 = np.array([23,4,5,10])
arr2 = np.array([10, 29, 3, 0])
print(arr1 + arr2)

In [9]:
print(arr + arr1)
print(arr1 + arr) #same

[[35  7  9 65]
 [45  4 38 12]]
[[35  7  9 65]
 [45  4 38 12]]


applying broadcasting in real life scenarios

In [15]:
 data = np.array([[10, 20, 30],
 [15, 25, 35],
 [20, 30, 40],
 [25, 35, 45],
 [30, 40, 50]])

mean = np.mean(data, axis = 0)
standard_dev = np.std(data, axis = 0)

normalized_Data = (data - mean) / standard_dev

print(normalized_Data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
